# Generated by Django 5.0.4 on 2024-08-06 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='auth_name',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
