# Generated by Django 5.0.4 on 2024-08-17 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0004_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='auth_name',
        ),
    ]
