# Generated by Django 5.0.4 on 2024-11-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0008_alter_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='clicks',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
