# Generated by Django 5.1.3 on 2024-12-04 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0009_post_clicks'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='video_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumbnails/'),
        ),
        migrations.AddField(
            model_name='post',
            name='video_url',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
    ]
