# Generated by Django 5.1.3 on 2024-12-06 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0010_post_video_thumb_post_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_thumb',
            field=models.ImageField(blank=True, null=True, upload_to='videos/thumb/'),
        ),
    ]
